name: ffmpeg_back_texxia
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  path: ^1.8.0
  dotenv: ^4.1.0
  envied: ^0.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
